[package]
name = "psd-to-png"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"] }
image = "0.25.1"
psd = "0.3.5"
walkdir = "2.5.0"
